api:
   test:
      response: This is the value

eureka: 
   client: 
      serviceUrl:
          defaultZone: http://eureka:eureka@localhost:8761/eureka/, http://eureka:eureka@localhost:8762/eureka/

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: secret
