api:
   test:
      response: This is the value Update

eureka: 
   client: 
      serviceUrl:
          defaultZone: http://eureka:eureka@localhost:8761/eureka/

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: secret


security:
      user:
        name: admin
        password: secret
management:
  security:
     roles:SUPERUSER
